### ISSUE TITLE
How to generate the A-site read density profiles?

### ISSUE THREAD

**Issue by worsteggs** [nabeel1990/Asite_LP_method#1]

**Comment by nabeel-bioinfo** [comment]
You can run the first script and add the following arguments.  -s indicates that A-site profiles be generated -p is the file containing the offset table for yeast as shown in the paper. This file is present in the data_files directory.

python src/asite_ip_preprocess.py -m 20 -x 35 -g data_files/sacCer3/CDS_info.tab -e data_files/sacCer3/sacCer3_R64-2-1_genome.fa -i  input.sam -s Yes -p data_files/sacCer3/A-site_IP_offset_table_yeast.tab

There is now a web interface based on these scripts to generate A-site profiles. Please visit https://a-site.vmhost.psu.edu/.

**Comment by worsteggs** [comment]
@nabeel-bioinfo 
Thanks for replying! I have seen the web interface, and it's a nice work!

But now I have another question. Since I use human data, how can I get the CDS_info.tab file like the yeast? Can I convert to it directly from the human genome gff3 file download from gencode project?

Thanks again for your nice work!

**Comment by worsteggs** [comment]
I get the CDS_info.tab file successfully by converting directly from the human genome gff3 file. I'll close this issue. Thanks for your help!
